### ISSUE TITLE
Variable bubbles for user to select while editing the status in the UI

### ISSUE THREAD

**Issue by 7kayoh** [RigidStudios/roblox-discord-presence#5]
While there's a readme.md set with all available variables, it is hard for people to memorise all of them, causing them to read the documentation again when they plan to modify the status.

Having a list of available variables as a bubble would benefit the end user, as they no longer have to find the repository's readme documentation every time when they want to make changes.

My suggestion is to add a tiny bottom bar in the status textbox, which will be visible if the textbox is focused, then there will be a set of variables, presented with the corresponding symbol. If the user do not know one of the icons' actual meaning, they can hover at it, which a tooltip will show up just at top of the icon.

![image](https://user-images.githubusercontent.com/40730127/113480829-f170be80-94c8-11eb-9286-4f88f819d3b1.png)
Like this, for instance.

**Comment by Error-Cezar** [comment]
Thank you for your suggestion, this will be added in the next update.
