### ISSUE TITLE
Http post failed

### ISSUE THREAD

**Issue by RooflOmg** [RigidStudios/roblox-discord-presence#9]
It says this each 5 seconds in the output. What do i do
![image](https://user-images.githubusercontent.com/52837330/136255400-d5710bdc-84f7-4d3a-9259-f8711aa0c176.png)
 
 i have HTTP requests enabled tho
![image](https://user-images.githubusercontent.com/52837330/136255477-dee04d9f-f258-411c-afa1-01fd33aa53d6.png)

**Comment by Lincoln-Muller** [comment]
yes

**Comment by Error-Cezar** [comment]
Can you explain more about your issues?
Did you enable the nodejs server before using the plugin?

**Comment by meqativ** [comment]
> Can you explain more about your issues? Did you enable the nodejs server before using the plugin?

ugh i really can't, I've got my pc screwed up alot in the time that has passed since i created this issue

don't remember enabling the nodejs server tho
